### ISSUE TITLE
[Error: Compass failed]

### ISSUE THREAD

**Issue by wzup** [planetoftheweb/responsive#5]
I have this error thrown on Windows 7 64 bit. What can it be?

```
C:\sbox\responsive>gulp
[16:59:51] Using gulpfile C:\sbox\responsive\gulpfile.js
[16:59:51] Starting 'watch'...
[16:59:51] Finished 'watch' after 16 ms
[16:59:51] Starting 'html'...
[16:59:51] Finished 'html' after 6.18 ms
[16:59:51] Starting 'js'...
[16:59:51] Finished 'js' after 4.17 ms
[16:59:51] Starting 'compass'...
[16:59:51] Finished 'compass' after 1.88 ms
[16:59:51] Starting 'move'...
[16:59:51] Finished 'move' after 1.13 ms
[16:59:51] Starting 'connect'...
[16:59:51] Finished 'connect' after 8.5 ms
[16:59:51] Starting 'default'...
[16:59:51] Finished 'default' after 5.47 μs
[16:59:51] Server started http://localhost:8080
[16:59:51] LiveReload started on port 35729
[16:59:52] LoadError on line ["55"] of C: cannot load such file -- susy
Run with --trace to see the full backtrace

[16:59:52] { [Error: Compass failed]
  message: 'Compass failed',
  fileName: 'C:\\sbox\\responsive\\components\\sass\\style.scss',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function] } }
```

**Comment by laharidas** [comment]
Getting this error: any solution ?Thanks in advance
--------------------------------------

[11:25:15] LoadError on line ["54"] of C: cannot load such file -- breakpoint
Run with --trace to see the full backtrace

[11:25:15] { [Error: Compass failed]
  message: 'Compass failed',
  fileName: 'c:\\Users\\hlahari\\desktop\\responsive\\components\\sass\\style.sc
ss',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function] } }

**Comment by planetoftheweb** [comment]
Looks like the breakpoint Sass library maybe didn't get installed

**Comment by victorsgu** [comment]
Hello, I am getting an error for compass when I run gulp. Any ideas? thanks.

    [21:29:28] 'c:\Program' is not recognized as an internal or external command, 
    operable program or   batch file.

    [21:29:28] { [Error: Compass failed]
    message: 'Compass failed',
    fileName: 'c:\\Users\\user\\documents\\responsive\\components\\sass\\styl
    e.scss',
    showStack: false,
    showProperties: true,
    plugin: 'gulp-compass',
    __safety: { toString: [Function] } }

**Comment by bounasserabdelouahab** [comment]
@victorsgu use `/c/path/to/file` instead of `c:\path\to\file`

**Comment by planetoftheweb** [comment]
My suggestion would be to make sure a compatible version or Ruby is installed and up to date.

**Comment by laharidas** [comment]
Thanks a lot. I love your all tutorials.
It helped me to redirect my career with more focus.

Thanks again
Lahari

On Sun, Feb 1, 2015 at 5:08 PM, Ray Villalobos <notifications@github.com>
wrote:

> My suggestion would be to make sure a compatible version or Ruby is
> installed and up to date.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/planetoftheweb/responsive/issues/5#issuecomment-72387170>
> .
>



-- 
Regards,
Haridas T. Lahari
****************************************************************************
Phone : 703-281-2917 (H) / 571-271-9892 (M)
Vienna, Virginia, USA
Web  http://www.Lahari.com <http://www.lahari.com/>
****************************************************************************

**Comment by MrsColombo** [comment]
Hi Roy, I can use your help. What's wrong with this message? It's an error number 20 or something. I had to install almost all the components manually. Susy and breakpoints were the last two. Bu I still get this error. Thank you for your help!

[11:41:57] LoadError on line ["54"] of /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- breakpoint
Run with --trace to see the full backtrace

[11:41:57] { [Error: Compass failed]
  message: 'Compass failed',
  fileName: '/Users/juliarietveld/Desktop/Lynda/components/sass/style.scss',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function] } }

**Comment by DanielDevelop** [comment]
I keep getting the same thing and can't figure out how to fix it either

[15:11:10] LoadError on line ["54"] of /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- susy
Run with --trace to see the full backtrace

[15:11:10] { [Error: Compass failed]
  message: 'Compass failed',
  fileName: '/Users/####/Desktop/responsive/components/sass/style.scss',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function] } }
^C[15:12:38] Server stopped

**Comment by Vyt45** [comment]
I have same exact problem and cannot get any further in the "Building a Responsive Single-Page Design" course. Really frustrating.

**Comment by pcaWeb** [comment]
+1 here - same error

**Comment by planetoftheweb** [comment]
If it can't load up susy, it means that it wasn't installed properly. Make sure you've installed Ruby and then run:

```
$ gem update
$ gem install susy
```

**Comment by pcaWeb** [comment]
Hi Ray,

ok, ran both of those but am still getting the same error.
Does the busy install actually create a folder/file anywhere in the project?

Paul

On 26 May 2015 at 16:09, Ray Villalobos <notifications@github.com> wrote:

> If it can't load up susy, it means that it wasn't installed properly. Make
> sure you've installed Ruby and then run:
>
> $ gem update
> $ gem install susy
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/planetoftheweb/responsive/issues/5#issuecomment-105557932>
> .
>



-- 

regards,

Paul Oaten
*pca*
*Web*01225 290964
http://web.pca-uk.com
paul@pca-uk.com
@pca_uk <http://twitter.com/pca_uk>

<http://uk.linkedin.com/in/pauloaten>/ FreeAgent Accounting Software
<http://fre.ag/33dnjddk>

**Comment by Vyt45** [comment]
I managed to resolve this issue by executing the following:
<code>sudo gem uninstall sass</code>
and
<code>gem install compass</code>

**Comment by planetoftheweb** [comment]
Thanks for sharing with the rest of the folks. It's probably just an old version of sass that was persisting.

**Comment by planetoftheweb** [comment]
Try uninstalling sass and reinstalling it (like the user above suggests. Susy is a Ruby installation, so it wouldn't create a folder anywhere.

**Comment by pcaWeb** [comment]
I have this working now. Here's what I had to do:-

- update Ruby to version 2.1.4
- uninstall sass (as suggested above)
- install compass (as above)
- run sudo gem update
- run sudo gem install susy
- edit styles.scss to include call: @import "susyone" instead of @import "susy"

This works but the terminal will issue warnings about deprecated multiline strings.
