### ISSUE TITLE
Compass doesn't compile

### ISSUE THREAD

**Issue by dfabarbosa** [planetoftheweb/responsive#6]
Hi,
I have a mac (OS X 10.10.2) and when I try running your code, the first time it compiles everything. The second time, it doesn't compile the sass components and the task "compass" never finishes. That task put the cpu up to 100%. I've searched for a solution and I can't find one, can you help me?

**Comment by planetoftheweb** [comment]
I'm not sure there's enough info for me to debug this. This might be your installation. Make sure you do a gem update to update your installed ruby dependencies.
