### ISSUE TITLE
Ho do I debug terminal error response

### ISSUE THREAD

**Issue by cmojarro** [planetoftheweb/responsive#7]
Hi,

I am a student at Columbia College and your tutorial surpases instruction in class, however, I am having trouble trying to debug error outputs. What do you make of this output which is uncontrolling in my browser website?

[15:49:08] DEPRECATION WARNING: Passing null, a non-string value, to unquote()
will be an error in future versions of Sass.
        on line 19 of /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_box-sizing.scss, in `box-sizing'
        from line 12 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/support/_box-sizing.scss, in `susy-box-sizing'
        from line 40 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/support/_support.scss, in `susy-support'
        from line 12 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/shared/_output.scss, in `output'
        from line 28 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/language/susy/_span.scss, in `span'
        from line 9 of /Users/cmo/Desktop/responsive/components/sass/modules/_nav.scss
        from line 26 of /Users/cmo/Desktop/responsive/components/sass/style.scss

[15:49:08] DEPRECATION WARNING: Passing null, a non-string value, to unquote()
will be an error in future versions of Sass.
        on line 19 of /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_box-sizing.scss, in `box-sizing'
        from line 12 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/support/_box-sizing.scss, in `susy-box-sizing'
        from line 40 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/support/_support.scss, in `susy-support'
        from line 12 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/shared/_output.scss, in `output'
        from line 28 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/language/susy/_span.scss, in `span'
        from line 32 of /Users/cmo/Desktop/responsive/components/sass/modules/_nav.scss
        from line 26 of /Users/cmo/Desktop/responsive/components/sass/style.scss

[15:49:10] DEPRECATION WARNING: Passing null, a non-string value, to unquote()
will be an error in future versions of Sass.
        on line 19 of /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_box-sizing.scss, in `box-sizing'
        from line 12 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/support/_box-sizing.scss, in `susy-box-sizing'
        from line 40 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/support/_support.scss, in `susy-support'
        from line 12 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/shared/_output.scss, in `output'
        from line 28 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/language/susy/_span.scss, in `span'
        from line 20 of /Users/cmo/Desktop/responsive/components/sass/modules/_hotelinfo.scss, in `@content'
        from line 62 of /Library/Ruby/Gems/2.0.0/gems/breakpoint-2.5.0/stylesheets/_breakpoint.scss, in `breakpoint'
        from line 19 of /Users/cmo/Desktop/responsive/components/sass/modules/_hotelinfo.scss
        from line 30 of /Users/cmo/Desktop/responsive/components/sass/style.scss

[15:49:10] DEPRECATION WARNING: Passing null, a non-string value, to unquote()
will be an error in future versions of Sass.
        on line 19 of /Library/Ruby/Gems/2.0.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_box-sizing.scss, in `box-sizing'
        from line 12 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/support/_box-sizing.scss, in `susy-box-sizing'
        from line 40 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/support/_support.scss, in `susy-support'
        from line 12 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/output/shared/_output.scss, in `output'
        from line 28 of /Library/Ruby/Gems/2.0.0/gems/susy-2.2.2/sass/susy/language/susy/_span.scss, in `span'
        from line 25 of /Users/cmo/Desktop/responsive/components/sass/modules/_hotelinfo.scss, in `@content'
        from line 62 of /Library/Ruby/Gems/2.0.0/gems/breakpoint-2.5.0/stylesheets/_breakpoint.scss, in `breakpoint'
        from line 23 of /Users/cmo/Desktop/responsive/components/sass/modules/_hotelinfo.scss
        from line 30 of /Users/cmo/Desktop/responsive/components/sass/style.scss

**Comment by rheeler2** [comment]
same here.

**Comment by rheeler2** [comment]
I think this link will ferret out.  Will f/u if I don't give up.  Lol.
http://stackoverflow.com/questions/25047718/how-to-double-the-gutter-width-in-larger-breakpoints-with-susy-2

**Comment by planetoftheweb** [comment]
Yeah, I'm stumped about this one. Do you know the timecode in the video that Eric talks about it. It's a pretty long video.

**Comment by planetoftheweb** [comment]
Anyways, it looks like a warning, not an error technically.

**Comment by rheeler2** [comment]
8 minutes but I 1.5 time on google.  Seems Susy has upgraded.  Still researching.  Thanks for the f/u. I love your videos and have learned so much.  Thank you, thank you, thank you.

**Comment by rheeler2** [comment]
Changed container to column-width.  Susy is now susy 2 and changed syntax.  Works!  Yippee.
