### ISSUE TITLE
@include border-box-sizing

### ISSUE THREAD

**Issue by uniquedesigns2003** [planetoftheweb/responsive#8]
I'm getting an error in the terminal when I save _variables.scss and the following the http://localhost:8080 web page: 

Error: Invalid CSS after "... rder-box-sizing": expected  " {", was  "; //uses border..."
on line 3 of /responsive/components/sass/_variables.scss 
from line 18 of /responsive/components/sass/style.scss 

On line 3 I have: 
@include border-box-sizing; //uses border box sizing like the old IE

**Comment by uniquedesigns2003** [comment]
I'm also getting an error in the terminal re the fontfamily: 

[13:55:26] { [Error:     error components/sass/style.scss (Line 25 of components/sass/_variables.scss: Invalid CSS after "$fontfamily		": expected selector or at-rule, was ": 'Exo 2', 'Hel...")
Compilation failed in 1 files.
]
  message: '\u001b[31m    error\u001b[0m components/sass/style.scss (Line 25 of components/sass/_variables.scss: Invalid CSS after "$fontfamily\t\t": expected selector or at-rule, was ": \'Exo 2\', \'Hel...")\n\u001b[31mCompilation failed in 1 files.\n\u001b[0m',
  fileName: '/Users/nigela/Desktop/responsive/components/sass/style.scss',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-compass',
  __safety: { toString: [Function] } }

**Comment by planetoftheweb** [comment]
I'm not clear as to what line number or white branch you're working with here, so please be more clear so I can try to help you. You should be able to compare what you have with the final code. These errors can be tough to debug with this little info.
